name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy build files to GitHub Pages repository
        run: |
          cp -r build/* ../howbizarre.github.io/
          cd ../howbizarre.github.io/
          git config --global user.email "howbizarre@gmail.com"
          git config --global user.name "howbizarre"
          git add .
          git commit -m "Update build files"
          git push origin main
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}