name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust the Node.js version as needed
      
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      
      - name: Copy built files to howbizarre.github.io
        run: |
          # Clone the howbizarre.github.io repository
          git clone https://github.com/howbizarre/howbizarre.github.io.git deploy
          
          # Copy the built files to the root of the deploy directory
          cp -r output/* deploy/
          
          # Commit and push changes
          cd deploy
          git config --local user.email "howbizarre@gmail.com"
          git config --local user.name "howbizarre"
          git add .
          git commit -m "Update built files"
          git push origin main
        
      - name: Clean up
        run: |
          rm -rf deploy
